-- MySQL Script generated by MySQL Workbench
-- jue 24 mar 2022 20:03:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`DIVISION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DIVISION` (
  `idDIVISION` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idDIVISION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ARBITROS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ARBITROS` (
  `idARBITROS` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido1` VARCHAR(45) NULL,
  `apellido2` VARCHAR(45) NULL,
  `nacionalidad` VARCHAR(45) NULL,
  `años_experiencia` INT NULL,
  PRIMARY KEY (`idARBITROS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRESIDENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRESIDENTE` (
  `idPRESIDENTE` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido1` VARCHAR(45) NULL,
  `apellido2` VARCHAR(45) NULL,
  `fecha_nac` DATE NULL,
  `nacionalidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idPRESIDENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ESTADIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESTADIOS` (
  `idESTADIOS` INT NOT NULL,
  `nombre` VARCHAR(40) NULL,
  `aforo` INT NULL,
  PRIMARY KEY (`idESTADIOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EQUIPOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EQUIPOS` (
  `idEQUIPOS` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fecha_fundacion` DATE NULL,
  `numero_socios` INT NULL,
  `PRESIDENTE_idPRESIDENTE` INT NOT NULL,
  `ESTADIOS_idESTADIOS` INT NOT NULL,
  `DIVISION_idDIVISION` INT NOT NULL,
  PRIMARY KEY (`idEQUIPOS`),
  INDEX `fk_EQUIPOS_PRESIDENTE1_idx` (`PRESIDENTE_idPRESIDENTE` ASC) VISIBLE,
  INDEX `fk_EQUIPOS_ESTADIOS1_idx` (`ESTADIOS_idESTADIOS` ASC) VISIBLE,
  INDEX `fk_EQUIPOS_DIVISION1_idx` (`DIVISION_idDIVISION` ASC) VISIBLE,
  CONSTRAINT `fk_EQUIPOS_PRESIDENTE1`
    FOREIGN KEY (`PRESIDENTE_idPRESIDENTE`)
    REFERENCES `mydb`.`PRESIDENTE` (`idPRESIDENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EQUIPOS_ESTADIOS1`
    FOREIGN KEY (`ESTADIOS_idESTADIOS`)
    REFERENCES `mydb`.`ESTADIOS` (`idESTADIOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EQUIPOS_DIVISION1`
    FOREIGN KEY (`DIVISION_idDIVISION`)
    REFERENCES `mydb`.`DIVISION` (`idDIVISION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PARTIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PARTIDOS` (
  `idPARTIDOS` INT NOT NULL,
  `ARBITROS_idARBITROS` INT NOT NULL,
  `GOLESLOCAL` INT NOT NULL,
  `GOLESVISITANTE` INT NOT NULL,
  PRIMARY KEY (`idPARTIDOS`),
  INDEX `fk_PARTIDOS_ARBITROS1_idx` (`ARBITROS_idARBITROS` ASC) VISIBLE,
  INDEX `fk_PARTIDOS_EQUIPOS1_idx` (`GOLESLOCAL` ASC) VISIBLE,
  INDEX `fk_PARTIDOS_EQUIPOS2_idx` (`GOLESVISITANTE` ASC) VISIBLE,
  CONSTRAINT `fk_PARTIDOS_ARBITROS1`
    FOREIGN KEY (`ARBITROS_idARBITROS`)
    REFERENCES `mydb`.`ARBITROS` (`idARBITROS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARTIDOS_EQUIPOS1`
    FOREIGN KEY (`GOLESLOCAL`)
    REFERENCES `mydb`.`EQUIPOS` (`idEQUIPOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARTIDOS_EQUIPOS2`
    FOREIGN KEY (`GOLESVISITANTE`)
    REFERENCES `mydb`.`EQUIPOS` (`idEQUIPOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`JUGADORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`JUGADORES` (
  `idJUGADORES` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido1` VARCHAR(45) NULL,
  `apellido2` VARCHAR(45) NULL,
  `nacionalidad` VARCHAR(45) NULL,
  `posicion` VARCHAR(45) NULL,
  `EQUIPOS_idEQUIPOS` INT NOT NULL,
  PRIMARY KEY (`idJUGADORES`),
  INDEX `fk_JUGADORES_EQUIPOS1_idx` (`EQUIPOS_idEQUIPOS` ASC) VISIBLE,
  CONSTRAINT `fk_JUGADORES_EQUIPOS1`
    FOREIGN KEY (`EQUIPOS_idEQUIPOS`)
    REFERENCES `mydb`.`EQUIPOS` (`idEQUIPOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
